FROM almalinux:9
#CMD ["ping", "google.com"]
CMD ["google.com"]
ENTRYPOINT ["ping"]

# in run time cmd overridden but we can not override entrypoint
# we can supply arguments to entrypoint through cmd 